from flask import Flask, request, jsonify, json
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import and_, or_
import os
import sys

# **alternate way to update changes to database without dropping schema and recreating**
# from flask_migrate import Migrate
### in terminal:
# flask db init
# flask db migrate -m "Initial migration"
# flask db upgrade
###
# migrate = Migrate(app, db)

# Initialize Flask app
app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL')
db = SQLAlchemy(app)

class SkinProds(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), unique=True, nullable = False)
    brand_name = db.Column(db.String(200), nullable = False)
    product_type = db.Column(db.String(200), nullable=True)
    skin_type = db.Column(db.String(200), default="Normal, Dry, Oily, Combo, Sensitive")
    ingredients = db.Column(db.String(1600),  nullable=False)
  
    
    def as_dict(self):
       return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    @property
    def serialize(self):
    #return serialized object
        return {
            'id' : self.id,
            'name' : self.name,
            'brand_name' : self.brand_name,
            'product_type' : self.product_type,
            'skin_type' : self.skin_type,
            'ingredients' : self.ingredients,
        }
  
    def __init__(self, name, brand_name, product_type, ingredients, skin_type="Normal, Dry, Oily, Combo, Sensitive"):
        self.name = name
        self.brand_name = brand_name
        self.product_type = product_type
        self.skin_type = skin_type
        self.ingredients = ingredients


# to instantiate skincare product records in previously initialized database SkinProds (78 products)
@app.route("/dbinit", methods=['GET'])
def dbinit():
    # db.session.add(User(username="example"))
    db.session.add(SkinProds(name="Hyaluronic Acid 2% + B5", brand_name="The Ordinary", product_type="Serum", ingredients="Water, Sodium Hyaluronate, Pentylene Glycol, Propanediol, Sodium Hyaluronate Crosspolymer, Panthenol, Ahnfeltia Concinna Extract, Glycerin, Trisodium Ethylenediamine Disuccinate, Citric Acid, Isoceteth-20, Ethoxydiglycol, Ethylhexylglycerin, Hexylene Glycol, 1,2-Hexanediol, Phenoxyethanol, Caprylyl Glycol"))    
    db.session.add(SkinProds(name="Niacinamide 10% + Zinc 1% Oil Control Serum", brand_name="The Ordinary", product_type="Serum", ingredients="Water, Niacinamide, Pentylene Glycol, Zinc PCA, Dimethyl Isosorbide, Tamarindus Indica Seed Gum, Xanthan gum, Isoceteth-20, Ethoxydiglycol, Phenoxyethanol, Chlorphenesin"))    
    db.session.add(SkinProds(name="Strawberry BHA Pore-Smooth Blur Drops", brand_name="Glow Recipe", product_type="Serum", ingredients="Water, Tapioca Starch, Isopentyldiol, Nylon-12, C9-12 Alkane, Distarch Phosphate, Ammonium Acryloyldimethyltaurate/VP Copolymer, Saccharide Isomerate, Fragaria Vesca (Strawberry) Leaf Extract, Salicylic Acid, Salix Alba Bark Extract, Fragaria Vesca (Strawberry) Fruit Extract, Leuconostoc/Radish Root Ferment Filtrate, Sodium Hyaluronate, Bisabolol, Coco-Caprylate/Caprate, Triheptanoin, Butylene Glycol, Pentylene Glycol, Propanediol, Caprylyl Glycol, Polyglyceryl-10 Dioleate, Dilinoleic Acid/Butanediol Copolymer, Polyglyceryl-10 Dipalmitate, Ethylhexylglycerin, Sodium Hydroxide, 1,2-Hexanediol, Phenoxyethanol, Castor Oil/IPDI Copolymer, Citric Acid, Fragrance/Parfum"))    
    db.session.add(SkinProds(name="Skin Perfecting 2% BHA Liquid Exfoliant", brand_name="Paula's Choice", product_type="Exfoliant", ingredients="Water, Methylpropanediol, Butylene Glycol, Salicylic Acid, Polysorbate 20, Camellia Oleifera (Green Tea) Leaf Extract, Sodium Hydroxide, Tetrasodium EDTA"))
    db.session.add(SkinProds(name="The Water Cream Oil-Free Pore Minimizing Moisturizer", brand_name="Tatcha", product_type="Moisturizer", ingredients="Water, Saccharomyces/Camellia Sinensis Leaf/Cladosiphon Okamuranus/Rice Ferment Filtrate, Dimethicone, Propanediol, Glycerin, Diglycerin, Diphenylsiloxy Phenyl Trimethicone, Gold, Belamcanda Chinensis Root Extract, Rosa Multiflora Fruit Extract, Houttuynia Cordata Extract, Sophora Angustifolia Root Extract, Sodium Hyaluronate, Lecithin, Pistacia Lentiscus (Mastic) Gum, Sodium Chloride, Sodium Citrate, Mica, Peg-9 Polydimethylsiloxyethyl Dimethicone, Dimethicone/Peg-10/15 Crosspolymer, Dimethicone/Phenyl Vinyl Dimethicone Crosspolymer, Disodium Edta, Tin Oxide, Titanium Dioxide, Butylene Glycol, Ethylhexylglycerin, Parfum/Fragrance, Alcohol, Phenoxyethanol, Hadasei-3"))
    db.session.add(SkinProds(name="Regenerist Micro-Sculpting Cream Moisturizer", brand_name="Olay", product_type="Moisturizer", ingredients="Water, Glycerin, Isohexadecane, Niacinamide, Isopropyl Isostearate, Aluminum Starch Octenylsuccinate, Nylon-12, Dimethicone, Panthenol, Tocopheryl Acetate, Palmitoyl Pentapeptide-4, Sodium Peg-7 Olive Oil Carboxylate, Sodium Hyaluronate, Caprylic/Capric Triglyceride, Ceratonia Siliqua (Carob) Fruit Extract, Stearyl Alcohol, Polyethylene, Cetyl Alcohol, Behenyl Alcohol, Sodium Acrylates Copolymer, Titanium Dioxide, Benzyl Alcohol, Methylparaben, Ethylparaben, Dimethiconol, Polyacrylamide, Fragrance, Peg-100 Stearate, Propylparaben, Cetearyl Glucoside, Cetearyl Alcohol, C13-14 Isoparaffin, Disodium Edta, Citric Acid, Stearic Acid, Palmitic Acid, C12-13 Pareth-3, Laureth-7, Sodium Hydroxide, Mica"))
    db.session.add(SkinProds(name="Superfood Antioxidant Cleanser", brand_name="Youth To The People", product_type="Cleanser", skin_type="Normal, Oily, Combo", ingredients="Water, Cocamidopropyl Hydroxysultaine, Sodium Cocoyl Glutamate, Sorbeth-230 Tetraoleate, Polysorbate 20, Sodium Chloride, Aloe Barbadensis Leaf (Aloe Vera) Juice Powder, Brassica Oleracea Acephala (Kale) Leaf Extract, Spinacia Oleracea (Spinach) Leaf Extract, Camellia Sinensis (Green Tea) Leaf Extract, Medicago Sativa (Alfalfa) Extract, Chamomilla Recutita (Matricaria) Flower Extract, Tetrahexyldecyl Ascorbate (Vitamin C), Glycerin, Panthenol (Vitamin B5), Tocopheryl Acetate (Vitamin E), Decyl Glucoside, Sorbitan Laurate, Tetrasodium Glutamate Diacetate, Gluconolactone, Ethylhexylglycerin, Maltodextrin, Citric Acid, Phenoxyethanol, Potassium Sorbate, Sodium Benzoate, Gardenia Jasminoides (Jasmine) Fruit Extract, Fragrance/Parfum, Sodium Hydroxide, Sodium Glycolate, Sodium Formate, Hexyl Cinnamal, Linalool, Limonene, Chlorophyllin-Copper Complex"))
    db.session.add(SkinProds(name="Relief Sun: Rice + Probiotics SPF50+ PA++++", brand_name="Beauty of Joseon", product_type="Sunscreen", ingredients="Water, Oryza Sativa (Rice) Extract (30%), Dibutyl Adipate, Propanediol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Polymethylsilsesquioxane, Ethylhexyl Triazone, Niacinamide, Methylene Bis-benzotriazolyl Tetramethylbutylphenol, Coco-caprylate/Caprate, Caprylyl Methicone, Diethylhexyl Butamido Triazone, Glycerin, Butylene Glycol, Oryza Sativa (Rice) Germ Extract, Camellia Sinensis Leaf Extract, Lactobacillus/Pumpkin Ferment Extract, Bacillus/Soybean Ferment Extract, Saccharum Officinarum (Sugarcane) Extract, Macrocystis Pyrifera (Kelp) Extract, Cocos Nucifera (Coconut) Fruit Extract, Panax Ginseng Root Extract, Camellia Sinensis Leaf Extract, Monascus/Rice Ferment, Pentylene Glycol, Behenyl Alcohol, Poly C10-30 Alkyl Acrylate, Polyglyceryl-3 Methylglucose Distearate, Decyl Glucoside, Tromethamine, Carbomer, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, 1,2-Hexanediol,Sodium Stearoyl Glutamate, Polyacrylate Crosspolymer-6, Ethylhexylglycerin, Adenosine, Xanthan Gum, Tocopherol, Lactobacillus/Rice Ferment, Aspergillus Ferment, Saccharomyces/Rice Ferment Filtrate"))
    db.session.add(SkinProds(name="Advanced Snail 96 Mucin Power Essence", brand_name="COSRX", product_type="Essence", ingredients="Snail Secretion Filtrate, Betaine, Butylene Glycol, 1,2-Hexanediol, Sodium Hyaluronate, Panthenol, Arginine, Allantoin, Ethyl Hexanediol, Sodium Polyacrylate, Carbomer, Phenoxyethanol"))
    db.session.add(SkinProds(name="Unseen Sunscreen SPF 40 PA+++", brand_name="Supergoop!", product_type="Sunscreen", ingredients="Avobenzone 3%, Homosalate 8%, Octisalate 5%, Octocrylene 4%, Isododecane, Dimethicone Crosspolymer, Dimethicone/Bis-Isobutyl PPG-20 Crosspolymer, Polymethylsilsesquioxane, Isohexadecane, Dicaprylyl Carbonate, Meadowfoam Estolide, Caprylic/Capric Triglyceride, Polyester-7, Neopentyl Glycol Diheptanoate, Lithothamnion Calcareum Extract, Caprylyl Glycol, Butyrospermum Parkii (Shea) Butter, Jojoba Esters, Mannitol, Olibanum, Lecithin, Microcrystalline Cellulose, Diatomaceous Earth, Zinc Sulfate, Silica, Tocopherol"))
    db.session.add(SkinProds(name="Faded Serum for Dark Spots & Discoloration", brand_name="Topicals", product_type="Serum", ingredients="Water, Caprylic/Capric Triglyceride, Glycerin, Niacinamide, Glyceryl Stearate, Tranexamic Acid, Butyrospermum Parkii (Shea) Butter, Simmondsia Chinensis (Jojoba) Seed Oil, Alpha-Arbutin, Behenyl Alcohol, Kojic Acid Dipalmitate, Gluthathione, Turmeric Butter, Ethylene Brassylate, Dimethylmethoxy Chromanyl Palmitate, Azelaic Acid, Glycyrrhiza Uralensis (Licorice) Root Extract, Melatonin, Phytic Acid, Squalane, Allantoin, Centella Asiatica Leaf Extract, Tocopherol, Arginine, Lecithin, Glycine Soja (Soybean) Sterols, Cetyl Palmitate, Ethylhexylglycerin, Sclerotium Gum, Zinc Ricinoleate, Cetearyl Alcohol, Sodium Lauroyl Sarcosinate, Tetrahydroxypropyl Ethylenediamine, Trisodium Ethylenediamine Disuccinate, Ceteareth-12, Ceteareth-20, Phenoxyethanol"))
    db.session.add(SkinProds(name="Protini Polypeptide Firming Moisturizer", brand_name="Drunk Elephant", product_type="Moisturizer", ingredients="Water, Dicaprylyl Carbonate, Glycerin, Cetearyl Alcohol, Cetearyl Olivate, Sorbitan Olivate, Sclerocarya Birrea Seed Oil, Bacillus/ Folic Acid Ferment Filtrate Extract, Nymphaea Alba Root Extract, sh-Oligopeptide-1, sh-Oligopeptide-2, sh-Polypeptide-1, sh-Polypeptide-9, sh-Polypeptide-11, Copper Palmitoyl Heptapeptide-14, Heptapeptide-15 Palmitate, Palmitoyl Tetrapeptide-7, Palmitoyl Tripeptide-1, Alanine, Arginine, Glycine, Histidine, Isoleucine, Phenylalanine, Proline, Serine, Threonine, Valine, Acetyl Glutamine, Coconut Alkanes, Coco-Caprylate/Caprate, Sodium Hyaluronate, Aspartic Acid, Linoleic Acid, Linolenic Acid, Lecithin, Butylene Glycol, Polyvinyl Alcohol, Sodium Lactate, Sodium PCA, PCA, Sorbitan Isostearate, Carbomer, Polysorbate 20, Polysorbate 60, Lactic Acid/Glycolic Acid Copolymer, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Xanthan Gum, Isomalt, 1,2-Hexanediol, Caprylyl Glycol, Chlorphenesin, Phenoxyethanol, Tocopherol, Sodium Benzoate, Phenylpropanol, Glyceryl Caprylate, Symphytum Officinale Callus Culture Extract"))
    db.session.add(SkinProds(name="Banana Bright+ Vitamin C Eye Creme", brand_name="OLEHENRIKSEN", product_type="Eye Cream", ingredients="Water, Simmondsia Chinensis (Jojoba) Seed Oil, Butyrospermum Parkii (Shea) Butter, Isododecane, Coconut Alkanes, 3-O-Ethyl Ascorbic Acid, Cetearyl Alcohol, Glycerin, Synthetic Beeswax, Dilinoleic Acid/Propanediol Copolymer, Polymethylsilsesquioxane, Cocoyl Proline, Dimethicone Crosspolymer, Pentaerythrityl Tetraisostearate, Tetrahexyldecyl Ascorbate, Ascorbic Acid, Colloidal Gold, Collagen, Glutathione, Citrus Nobilis (Mandarin Orange) Fruit Extract, Citrus Paradisi (Grapefruit) Peel Extract, Glucosyl Hesperidin, Tocopherol, Tamarindus Indica Seed Polysaccharide, Poncirus Trifoliata Fruit Extract, Morus Alba Root Extract, Linoleic Acid, Linolenic Acid, Jojoba Esters, Caprylyl Glycol, Coco-Caprylate/Caprate, Propanediol, Polyglyceryl-3 Cocoate, Polyglyceryl-4 Caprate, Polyglyceryl-6 Caprylate, Polyglyceryl-6 Ricinoleate, Hdi/Trimethylol Hexyllactone Crosspolymer, Polyacrylate-13, Butylene Glycol, Polyglyceryl-3 Stearate, Polysorbate 20, Sodium Citrate, Polyisobutene, Beheneth-5, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Behenyl Alcohol, Sodium Hydroxide, Sorbic Acid, Sorbitan Isostearate, Citric Acid, Sorbitol, Silica, Sodium Benzoate, 1,2-Hexanediol, Xanthan Gum, Phenoxyethanol, Leuconostoc/Radish Root Ferment Filtrate, Mica, Titanium Dioxide, Iron Oxides"))
    db.session.add(SkinProds(name="Virgin Marula Luxury Face Oil", brand_name="Drunk Elephant", product_type="Face Oil", ingredients="100% Unrefined Sclerocraya Birrea (Marula) Kernel Oil"))
    db.session.add(SkinProds(name="100% Pure Argan Oil", brand_name="Josie Maran", product_type="Face Oil", ingredients="100% Pure Organic Argan Oil"))
    db.session.add(SkinProds(name="Pure Vitamin C Face Serum with Salicylic Acid", brand_name="La Roche-Posay", product_type="Serum", ingredients="Water, Ascorbic Acid, Cyclohexasiloxane, Glycerin, Alcohol Denat., Potassium Hydroxide, Polymethylsilsesquioxane, Polysilicone-11, Dimethicone, Propylene Glycol, Pentaerythrityl Tetraethylhexanoate, C13-14 Isoparaffin, Tocopherol, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Adenosine, Acetyl Dipeptide-1 Cetyl Ester, Peg-20 Methyl Glucose Sesquistearate, Poloxamer 338, Salicylic Acid, Polyacrylamide, Toluene Sulfonic Acid, Ammonium Polyacryloyldimethyl Taurate, Xanthan Gum, Caprylyl Glycol, Disodium Edta, Bht, Laureth-7, Parfum/Fragrance"))
    db.session.add(SkinProds(name="Effaclar Duo Dual Acne Treatment with Benzoyl Peroxide", brand_name="La Roche-Posay", product_type="Acne Spot Treatment", ingredients="Benzoyl Peroxide 5.5% (Acne Medication), Water, Isostearyl Alcohol, Glycerin, Pentylene Glycol, Silica, Carbomer, Capryloyl Salicylic Acid, Potassium Hydroxide, Tocopheryl Acetate, Acrylates/c10-30 Alkyl Acrylate Crosspolymer, Disodium EDTA, Epilobium Angustioflium Flower/leaf/stem Extract"))
    db.session.add(SkinProds(name="Drying Lotion", brand_name="Mario Badescu", product_type="Acne Spot Treatment", ingredients="Isopropyl Alcohol, Water, Calamine, Camphor, Sulfur, Resorcinol, Salicylic Acid, Zinc Oxide, Titanium Dioxide, Talc, Glycerin"))
    db.session.add(SkinProds(name="Eye Duty Niacinamide Brightening Eye Cream", brand_name="First Aid Beauty", product_type="Eye Cream", ingredients="Water, Dimethicone, Glycerin, Sea Water, Butylene Glycol, Niacinamide, Polysilicone-11, Caprylic/Capric Triglyceride, Mica, Panthenol, Gigartina Stellata/Kappaphycus Alvarezii Extract, Sodium Ascorbyl Phosphate, Coffea Arabica (Coffee) Seed Extract, Sodium Hyaluronate, Caffeine, Cucurbita Pepo (Pumpkin) Seed Extract, Corallina Officinalis Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Chrysanthemum Parthenium (Feverfew) Extract, Camellia Sinensis Leaf Extract, Tocopherol, Phytosteryl/Octyldodecyl Lauroyl Glutamate, Sodium Acrylates Copolymer, Hydroxyacetophenone, Glyceryl Polyacrylate, Squalane, Hydrogenated Polycyclopentadiene, Polyacrylate Crosspolymer-6, Lecithin, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Caprylyl Glycol, Linoleic Acid, Phytosteryl Canola Glycerides, Silica, Hexylene Glycol, Palmitic Acid, Oleic Acid, Stearic Acid, Sorbitan Isostearate, Polysorbate 60, Triolein, T-Butyl Alcohol, Phenoxy-Ethanol, Sodium Benzoate, Potassium Sorbate, Citric Acid, Titanium Dioxide, Iron Oxides"))
    db.session.add(SkinProds(name="Avocado Ceramide Moisture Barrier Cleanser", brand_name="Glow Recipe", product_type="Cleanser", ingredients="Water, Glycerin, Acrylates Copolymer, Potassium Cocoyl Glycinate, Persea Gratissima (Avocado) Oil, Lauramidopropyl Betaine, Potassium Cocoate, Glycolipids, Inulin, Ceramide NP, Avena Sativa (Oat) Kernel Flour, Persea Gratissima (Avocado) Fruit Extract, Populus Tremuloides Bark Extract, Saccharide Isomerate, Polyglyceryl-4 Caprate, Polyglyceryl-6 Caprylate,1,2-Hexanediol, Caprylyl Glycol, Hydroxyacetophenone, Myristamidopropyl Betaine, Sodium Chloride, Lauroyl Lysine, Phytosteryl/Octyldodecyl Lauroyl Glutamate, Sodium Hydroxide, Citric Acid, Sodium Citrate, Caprylyl Glyceryl Ether, Caprylic/Capric Triglyceride, Elettaria Cardamomum Seed Extract, Jasminum Officinale (Jasmine) Flower/Leaf Extract, Camellia Sinensis Leaf Extract, Cananga Odorata Flower Extract, Cucumis Melo (Melon) Fruit Extract, Cucumis Sativus (Cucumber) Fruit Extract, Lavandula Angustifolia (Lavender) Flower/Leaf/Stem Extract, Pyrus Malus (Apple) Fruit Extract, Rose Extract, Rubus Idaeus (Raspberry) Leaf Extract, Santalum Album (Sandalwood) Wood Extract, Melia Azadirachta Leaf Extract, Amber Powder, Coccinia Indica Fruit Extract, Melia Azadirachta Flower Extract, Tocopherol, Solanum Melongena (Eggplant) Fruit Extract, Ocimum Basilicum (Basil) Flower/Leaf Extract, Curcuma Longa (Turmeric) Root Extract, Corallina Officinalis Extract"))
    db.session.add(SkinProds(name="Find Your Balance Oil Control Cleanser", brand_name="OLEHENRIKSEN", product_type="Cleanser", skin_type="Oily, Combo", ingredients="Water, Sodium Cocoyl Isethionate, Decyl Glucoside, Cocamidopropyl Betaine, Glycerin, Acrylates Copolymer, Glycol Distearate, Phenoxyethanol, Glycolic Acid, Lactic Acid, Sodium Hydroxide, Caprylyl Glycol, Eucalyptus Globulus Leaf Oil, Mentha Piperita (Peppermint) Oil, Laureth-4, Ethylhexylglycerin, Hexylene Glycol, Melia Azadirachta Seed Oil, Linoleic Acid, Camellia Sinensis Leaf Extract, Chonrus Crispus (Carrageenan) Extract, Eucalyptus Globulus Leaf Extract, Macrocystis Pyrifera (Kelp) Extract, Phytic Acid, Linolenic Acid, Sodium Benzoate, Tocopherol, Limonene"))
    db.session.add(SkinProds(name="Vinopure Natural Salicylic Acid Pore Minimizing Serum", brand_name="Caudalie", product_type="Serum", skin_type="Oily, Combo", ingredients="Water, Rosa Damascena Flower Water, Alcohol, Niacinamide, Butylene Glycol, Palmitoyl Grape Seed Extract, Xanthan Gum, Salicylic Acid, Sodium Hyaluronate, Tocopherol, Pelargonium Graveolens Flower Oil, Sodium Hydroxide, Mentha Piperita (Peppermint) Oil, Citral, Cymbopogon Citratus Leaf Oil, Rosmarinus Officinalis (Rosemary) Leaf Oil, Citronellol, Geraniol, Sodium Phytate, Linalool, Lavandula Hybrida Oil, Melissa Officinalis Leaf Oil, Limonene"))
    db.session.add(SkinProds(name="Calendula Herbal Extract Alcohol Free Toner", brand_name="Kiehl's", product_type="Toner", skin_type="Combo", ingredients="Water, Propylene Glycol, Pentylene Glycol, Methylparaben, Disodium EDTA, Arctium Lappa Extract/Arctium Lappa Root Extract, Calendula Officinalis Extract/Calendula Officinalis Flower Extract, Calendula Officinalis Flower Extract, Hydrolyzed Corn Starch, Allantoin, Hedera Helix Extract - Ivy Leaf/Stem Extract, Althaea Officinalis/Althaea Officinalis Root Extract"))
    db.session.add(SkinProds(name="Effaclar Mat", brand_name="La Roche-Posay", product_type="Moisturizer", skin_type="Oily", ingredients="Water, Glycerin, Dimethicone, Isocetyl Stearate, Alcohol Denat., Silica, Dimethicone/Vinyl Dimethicone Crosspolymer, Acrylamide/Sodium Acryloyldimethyltaurate Copolymer, Methyl Methacrylate Crosspolymer, Butylene Glycol, PEG-100 Stearate, Cocamide Mea, Sarcosine, Glyceryl Stearate, Triethanolamine, Isohexadecane, Perlite, Capryloyl Salicylic Acid, Tetrasodium EDTA, Pentylene Glycol, Polysorbate 80, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Salicylic Acid, Parfum/Fragrance"))
    db.session.add(SkinProds(name="Ulta Repair Cream Intense Hydration", brand_name="First Aid Beauty", product_type="Moisturizer", skin_type="Normal, Dry, Combo", ingredients="Snail Secretion Filtrate, Betaine, Butylene Glycol, 1,2-Hexanediol, Sodium Hyaluronate, Panthenol, Arginine, Allantoin, Ethyl Hexanediol, Sodium Polyacrylate, Carbomer, Phenoxyethanol"))
    db.session.add(SkinProds(name="Beste No.9 Gelly Cleanser", brand_name="Drunk Elephant", product_type="Cleanser", ingredients="Colloidal Oatmeal 0.50%, Water, Stearic Acid, Glycerin, C12-15 Alkyl Benzoate, Caprylic/Capric Triglyceride, Glyceryl Stearate, Glyceryl Stearate SE, Cetearyl Alcohol, Butyrospermum Parkii (Shea) Butter, Dimethicone, Squalane, Phenoxyethanol, Caprylyl Glycol, Xanthan Gum, Allantoin, Sodium Hydroxide, Disodium EDTA, Chrysanthemum Parthenium (Feverfew) Extract, Camellia Sinensis Leaf Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Ceramide NP, Eucalyptus Globulus Leaf Oil"))
    db.session.add(SkinProds(name="Like Butter Mask for Dry, Sensitive & Eczema-Prone Skin", brand_name="Topicals", product_type="Face Mask", ingredients="Water, Caprylic/Capric Triglyceride, Niacinamide, Squalane, Glycerin, Pentylene Glycol, Cetearyl Alcohol, Capryloyl Glycerin/Sebacic Acid Copolymer, Butyrospermum Parkii (Shea) Butter, Diheptyl Succinate, Glyceryl Stearate, Sorbitan Stearate, Oenothera Biennis (Evening Primrose) Oil, Madecassoside, Angelica Polymorpha Sinensis Root Extract, Rheum Palmatum Root Extract, Astragalus Membranaceus Extract, Curcuma Longa (Turmeric) Root Extract, Arnica Montana Flower Extract, Avena Sativa (Oat) Kernel Flour, Licorice Root (Glycyrrhiza Uralensis) Extract, Sodium Hyaluronate, Phytosphingosine, Sodium PCA, Ceramide EOP, Ceramide AP, Ceramide NP, Alanine, Serine, Aspartic Acid, Valine, Threonine, Proline, Arginine, Phenylalanine, Histidine, Palmitic Acid, Isoleucine, PCA, Lauroyl Lysine, Tocopherol, Cholesterol, Stearic Acid, Sodium Lactate, Propylene Glycol, Ethylhexylglycerin, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Cetearyl Glucoside, Sodium Lauroyl Lactylate, Carbomer, Xanthan Gum, Phenoxyethanol"))
    db.session.add(SkinProds(name="Cica Sleeping Mask", brand_name="Laneige", product_type="Face Mask", skin_type="Normal", ingredients="Water, Propanediol, Cetyl Ethylhexanoate, Squalane, Hydrogenated Poly(C6-14 Olefin), Glycerin, Panthenol, Cetearyl Alcohol, Butyrospermum Parkii (Shea) Butter, Glyceryl Stearate Citrate, 1,2-Hexanediol, Polyglyceryl-3 Methylglucose Distearate, Polyglyceryl-10 Stearate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Butylene Glycol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Glyceryl Caprylate, Ethylhexylglycerin, Disodium Edta, Asiaticoside, Madecassic Acid, Sorbitan Isostearate, Asiatic Acid, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Aureobasidium Pullulans Ferment, Chamaecyparis Obtusa Leaf Extract, Cymbopogon Martini Oil, Tocopherol"))
    db.session.add(SkinProds(name="Tea Elixir Skin Resilience Activating Serum", brand_name="fresh", product_type="Serum", ingredients="Water, Glycerin, Simmondsia Chinensis (Jojoba) Seed Oil, Helianthus Annuus (Sunflower) Seed Oil, Isostearyl Alcohol, Propanediol, 1,2-Hexanediol, Niacinamide, Pentylene Glycol, Butylene Glycol Cocoate, Cellulose, Macrocystis Pyrifera (Kelp) Extract, Camellia Sinensis Leaf Extract, Argania Spinosa Kernel Oil, Hyaluronic Acid, Ceramide Np, Tocopheryl Acetate, Tocopherol, Maltodextrin, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Parfum (Fragrance), Ethylcellulose, Xanthan Gum, Sodium Hyaluronate, Sodium Hydroxide, Adenosine, Biosaccharide Gum-1, Phytosphingosine, Hydrogenated Lecithin, Chlorphenesin, Potassium Sorbate, Sodium Benzoate, Limonene, Linalool, Citronellol, Geraniol"))
    db.session.add(SkinProds(name="Vinoclean Moisturizing Toner with Rose Water", brand_name="Caudalie", product_type="Toner", ingredients="Water, Butylene Glycol, Rosa Damascena Flower Water, Saccharide Isomerate, Methylpropanediol, Sodium Benzoate, Caprylyl Glycol, Citric Acid, Phenylpropanol, Sodium Carboxymethyl Betaglucan, Sodium Citrate"))
    db.session.add(SkinProds(name="Super Spot Remover Acne Treatment Gel", brand_name="Origins", product_type="Acne Spot Treatmnet", skin_type="Normal, Dry, Oily", ingredients="Water, Alcohol Denat., Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Salicylic Acid, Hamamelis Virginiana (Witch Hazel), Eugenia Caryophyllus (Clove) Bud Oil, Origanum Heracleoticum Flower Oil, Eugenol, Limonene, Cucumis Sativus (Cucumber) Fruit Extract, Pyrus Malus (Apple) Fruit Extract, Scutellaria Baicalensis Root Extract, Algae Extract, Poria Cocos Sclerotium Extract, Laminaria Saccharina Extract, Lactobacillus Ferment, Glycerin, Caffeine, Butylene Glycol, Tocopheryl Acetate, Magnesium Ascorbyl Phosphate, Sodium Hydroxide, Phenoxyethanol"))
    db.session.add(SkinProds(name="GinZing Into the Glow Brightening Serum", brand_name="Origins", product_type="Serum", skin_type="Normal, Combo", ingredients="Snail Secretion Filtrate, Betaine, Butylene Glycol, 1,2-Hexanediol, Sodium Hyaluronate, Panthenol, Arginine, Allantoin, Ethyl Hexanediol, Sodium Polyacrylate, Carbomer, Phenoxyethanol"))
    db.session.add(SkinProds(name="Resveratrol Lift Instant Firming Retinol Alternative Serum", brand_name="Caudalie", product_type="Serum", skin_type="Normal, Dry", ingredients="Water, Butylene Glycol, Glycerin, Hexyldecanol, Hexyldecyl Laurate, Squalane, Tocopheryl Acetate, Palmitoyl Grapevine Shoot Extract, C20-22 Alkyl Phosphate, C20-22 Alcohols, Potassium Cetyl Phosphate, Polyacrylate Crosspolymer-6, Caprylyl Glycol, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Hydrolyzed Hyaluronic Acid, Sodium Dehydroacetate, Hyaluronic Acid, Adenosine, Sodium Hydroxide, Acetyl Dipeptide-1 Cetyl Ester, Sodium Phytate, Khaya Senegalensis Bark Extract, Maltodextrin, Paeonia Lactiflora Root Extract, Parfum (Fragrance), Linalool, Limonene, Coumarin"))
    db.session.add(SkinProds(name="The Essence Skincare Boosting Treatment", brand_name="Tatcha", product_type="Essence", ingredients="Saccharomyces/Rice Ferment Filtrate, Propanediol, Camellia Sinensis Leaf Extract, Cladosiphon Okamuranus Extract, Ethylhexylglycerin, Phenoxyethanol"))
    db.session.add(SkinProds(name="Facial Treatment Essence (Pitera Essence)", brand_name="SK-II", product_type="Essence", ingredients="Galactomyces Ferment Filtrate, Butylene Glycol, Pentylene Glycol, Water, Sodium Benzoate, Methylparaben, Sorbic Acid"))
    db.session.add(SkinProds(name="Absolue Soft Cream Revitalizing & Brightening Moisturizer", brand_name="Lancome", product_type="Moisturizer", ingredients="Water, Glycerin, Hydrogenated Polyisobutene, Dimethicone, Butylene Glycol, Bis-Behenyl/Isostearyl/Phytosteryl Dimer Dilinoleyl Dimer Dilinoleate, Butyrospermum Parkii Butter/Shea Butter, Limnanthes Alba Seed Oil/Meadowfoam Seed Oil, Stearyl Alcohol, C30-45 Alkyl Dimethicone, Peg-20 Stearate, Silica, Panthenol, Hydroxypropyl Tetrahydropyrantriol, Peg-100 Stearate, Glyceryl Stearate, Octyldodecanol, Propanediol, Propylene Glycol, Phenoxyethanol, Ammonium Polyacryloyldimethyl Taurate, Chlorphenesin, Rose Extract, Caprylyl Glycol, Carbomer, Capryloyl Salicylic Acid, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Potassium Hydroxide, Tetrasodium Edta, Adenosine, Hydrolyzed Linseed Extract, Zea Mays Oil/Corn Oil, Prunus Armeniaca Kernel Oil/Apricot Kernel Oil, Passiflora Edulis Seed Oil, Oryza Sativa Bran Oil/Rice Bran Oil, Caramel, Limonene, Tetrasodium Glutamate Diacetate, Linalool, Peg-30 Dipolyhydroxystearate, Rosa Damascena Flower Oil, Trideceth-6, Alcohol, Citronellol, Geraniol, Sodium Benzoate, Tocopherol, Coumarin, Rosa Centifolia Flower Extract, Red 4, Yellow 5, Citric Acid, Ascorbyl Palmitate, Parfum/Fragrance"))
    db.session.add(SkinProds(name="Dewy Glow Moisturizer with Cherry Blossom & Niacinamide", brand_name="innisfree", product_type="Moisturizer", ingredients="Water, Glycerin, Propanediol, Dipropylene Glycol, Niacinamide, Betaine, 1,2-Hexanediol, Carbomer, Tromethamine, Ammonium Acryloyldimethyltaurate/Beheneth-25 Methacrylate Crosspolymer, Disodium EDTA, Ethylhexylglycerin, Fragrance/Parfum, Prunus Yedoensis Leaf Extract, Tocopherol"))
    db.session.add(SkinProds(name="RESIST Advanced Replenishing Toner with Hyaluronic Acid", brand_name="Paula's Choice", product_type="Toner", skin_type="Normal, Dry", ingredients="Water, Cyclopentasiloxane, Glycerin, Glycerth-26, Polysorbate 20, Dimethiconol, Linoleic Acid, Oleic Acid, Linolenic Acid, Phospholipids, Carnosine, Epigallocatechin Gallate, Genistein, Sodium Hyaluronate, Sphingolipids, Ferulic Acid, Laurdimonium Hydroxypropyl Hydrolyzed Soy Protein, Glycyrrhiza Glabra (Licorice) Root Extract, Acetyl Glucosamine, Quercetin, Oenothera Biennis (Evening Primrose) Oil, Beta Vulgaris (Beet) Root Extract, Cucurbita Pepo (Pumpkin) Seed Extract, Lecithin, Caprylic/Capric Triglyceride, Hydrolyzed Corn Starch, Hydrogenated Lecithin, Palmitic Acid, Butylene Glycol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Xanthan Gum, Laureth-23, Laureth-4, Aminomethyl Propanol, Disodium EDTA, Sodium Benzoate, Ethylhexylglycerin, Phenoxyethanol, Chlorphenesin, Benzoic Acid, Sorbic Acid"))
    db.session.add(SkinProds(name="Ultra Repair Wild Oat Hydrating Toner", brand_name="First Aid Beauty", product_type="Toner", skin_type="Normal, Dry, Combo", ingredients="Water, Glycerin, Glycereth-26, Squalane, Sorbitan Oleate, Phenoxyethanol, Ethylhexyl Salicylate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Colloidal Oatmeal, Mel (Honey, Miel), Saccharomyces/Honey Ferment Filtrate, Chrysanthemum Parthenium (Feverfew) Extract, So-dium Hydroxide, Potassium Sorbate, Avena Sativa (Oat) Kernel Extract, Sodium Benzoate, Citric Acid, Beta-Glucan, Camellia Sinensis Leaf Extract, Glycyrrhiza Glabra (Licorice) Root Ex-tract, Propolis Extract, Sodium Hyaluronate, Xanthan Gum, Ethylhexylglycerin, Tetrasodium EDTA, Chlorphenesin, Benzoic Acid, Sorbic Acid"))
    db.session.add(SkinProds(name="Soy Hydrating Gentle Face Cleanser", brand_name="fresh", product_type="Cleanser", ingredients="Water, Coco-Glucoside, Butylene Glycol, Glycerin, Propanediol, Xanthan Gum, 1,2-Hexanediol, Polyglyceryl-10 Laurate, Centaurea Cyanus Flower Water, Cucumis Sativus (Cucumber) Fruit Extract, Helianthus Annuus (Sunflower) Seed Oil, Borago Officinalis Seed Oil, Hydrolyzed Soy Protein, Rosa Damascena Extract, Rosa Damascena Flower Water, Aloe Barbadensis Leaf Juice, Panax Ginseng Root Extract, Malva Sylvestris (Mallow) Flower Extract, Rosa Damascena Flower Oil, Tocopherol, Caprylic/Capric Triglyceride, Caprylyl Glycol, Hydrolyzed Jojoba Esters, Silica, Citric Acid, Pentylene Glycol, Caramel, Sodium Hydroxide, Sodium Benzoate, Potassium Sorbate"))
    db.session.add(SkinProds(name="Daily Microfoliant Exfoliator", brand_name="Dermalogica", product_type="Exfoliant", skin_type="Normal, Combo, Oily", ingredients="Microcrystalline Cellulose, Magnesium Oxide, Sodium Cocoyl Isethionate, Colloidal Oatmeal, Disodium Lauryl Sulfosuccinate, Sodium Lauroyl Glutamate, Oryza Sativa (Rice) Bran Extract, Oryza Sativa (Rice) Starch, Hydrogenated Coconut Acid, Allantoin, Papain, Salicylic Acid, Ginkgo Biloba Leaf Extract, Camellia Sinensis Leaf Extract, Glycyrrhiza Glabra (Licorice) Root Extract, PCA, Populus Tremuloides Bark Extract, Cyclodextrin, Sodium Isethionate, Lauryl Methacrylate/Glycol Dimethacrylate Copolymer, Maltodextrin, Melaleuca, Alternifolia (Tea Tree) Leaf Oil, Citrus Paradisi (Grapefruit) Peel Oil, Sodium Dehydroacetate, Hydrolyzed Corn Starch Hydroxyethyl Ether, Water/Aqua/Eau, Limonene, Citric Acid"))
    db.session.add(SkinProds(name="Positively Radiant Skin Brightening Daily Scrub", brand_name="Aveeno", product_type="Exfoliant", ingredients="Water, Glycerin, Sodium Laureth Sulfate, Cellulose, Lauryl Glucoside, PEG-16 Soy Sterol, Acrylates/ C10-30 Alkyl Acrylate Crosspolymer, Phenoxyethanol, Glycol Distearate, Methylparaben, Laureth-4, Butylene Glycol, Fragrance, Sodium Hydroxide, Disodium EDTA, Cocamidopropyl Betaine, Glycine Soja (soybean) Protein, Citric Acid"))
    db.session.add(SkinProds(name="Aveeno Calm + Restore Redness Relief Foaming Facial Cleanser", brand_name="Aveeno", product_type="Cleanser", ingredients="Water, Cocamidopropyl Betaine, Glycerin, Decyl Glucoside, Sodium Hydrolyzed Potato Starch Dodecenylsuccinate, Sodium Chloride, Citric Acid, Sodium Benzoate, Potassium Acrylates Copolymer, Linoleamidopropyl PG-Dimonium Chloride Phosphate, Disodium EDTA, Sodium Hydroxide, Chrysanthemum Parthenium (Feverfew) Flower/Leaf/Stem Juice"))
    db.session.add(SkinProds(name="The Rice Polish Foaming Enzyme Powder", brand_name="Tatcha", product_type="Exfoliant", ingredients="Microcrystalline Cellulose, Oryza Sativa (Rice) Powder, Sodium Lauryl Phosphate, Sodium Lauroyl Glutamate, Sodium Stearoyl Glutamate, Aqua/Water/Eau, Sodium Cocoyl Glutamate, Lauryl Betaine, Sodium Lauroyl Methylaminopropionate, Saccharomyces/Camellia Sinensis Leaf/Cladosiphon Okamuranus/Rice Ferment Filtrate*, Papain, Oryza Sativa (Rice) Bran Extract, Sericin, Hydrolyzed Silk, Hydrolyzed Conchiolin Protein, Propanediol, Dextrin, Phytosteryl/Octyldodecyl Lauroyl Glutamate, Ethylhexylglycerin, Tocopherol, Butylene Glycol, Alcohol, Phenoxyethanol"))
    db.session.add(SkinProds(name="Daily UV Defense Invisible Broad Spectrum SPF 36 Sunscreen", brand_name="innisfree", product_type="Sunscreen", ingredients="Water, Butylene Glycol, Cyclopentasiloxane, Butyloctyl Salicylate, Ethylhexyl Methoxycrylene, Arachidyl Alcohol, Behenyl Alcohol, Glyceryl Stearate, Peg-100 Stearate, 1,2-Hexanediol, Polymethylsilsesquioxane, Cetyl Alcohol, Arachidyl Glucoside, Phenoxyethanol, Propanediol, Polyacrylate Crosspolymer-6, Octyldodecanol, Fragrance/Parfum, Xanthan Gum, Centella Asiatica Extract, Portulaca Oleracea Extract, Echium Plantagineum Seed Oil, T-Butyl Alcohol, Camellia Sinensis Leaf Extract, Ethylhexylglycerin, Helianthus Annuus (Sunflower) Seed Oil Unsaponifiables, Cardiospermum Halicacabum Flower/Leaf/Vine Extract, Tocopherol, Helianthus Annuus (Sunflower) Seed Oil, Glycerin, Hamamelis Virginiana (Witch Hazel) Leaf Extract, Citrus Unshiu Peel Extract, Opuntia Coccinellifera Fruit Extract, Orchid Extract, Camellia Japonica Leaf Extract, Citric Acid, Sodium Benzoate, Potassium Sorbate"))
    db.session.add(SkinProds(name="Clear Sunscreen Stick SPF 50+", brand_name="Shiseido", product_type="Sunscreen", ingredients="Avobenzone 2.5%, Homosalate 10.0%, Octisalate 5.0%, Octocrylene 10.0%, Diphenylsiloxy Phenyl Trimethicone, Mineral Oil, Hydroxystearic Acid, Triethylhexanoin, PEG/PPG-9/2 Dimethyl Ether,Methyl Methacrylate Crosspolymer,Dibutyl Lauroyl Glutamide,C12-15 Alkyl Benzoate,Polyamide-8,Silica Dimethyl Silylate,Tocopheryl Acetate,PEG/PPG-14/7 Dimethyl Ether,Lecithin,Glycyrrhiza Glabra (Licorice) Root Extract,PPG-17, Castor Oil/Ipdi Copolymer, Caprylic/Capric Triglyceride,BHT, Tocopherol, PEG-6,Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Silica, Fragrance"))
    db.session.add(SkinProds(name="Ultimune Power Infusing Anti-Aging Serum", brand_name="Shiseido", product_type="Serum", ingredients="Water, Sd Alcohol 40-B (Alcohol Denat.),Glycerin,Butylene Glycol, Dimethicone,Diglycerin,Peg/Ppg-17/4 Dimethyl Ether,Phenoxyethanol,Triethylhexanoin,Isodecyl Neopentanoate,Trehalose,Ammonium Acryloyldimethyltaurate/Beheneth-25 Methacrylate Crosspolymer,Peg-14m,Acrylates/C10-30 Alkyl Acrylate Crosspolymer,Peg/Ppg-14/7 Dimethyl Ether,Tocopheryl Acetate,Rosa Damascena Flower Water,Alcohol,Fragrance (Parfum),Disodium Edta,Potassium Hydroxide,Silica,Isoceteth-10,Linalool,Lauryl Betaine,Sodium Metabisulfite,Ginkgo Biloba Leaf Extract,Geraniol,Citronellol,Origanum Majorana Leaf Extract,Nelumbo Nucifera Germ Extract,Hydroxyproline,Houttuynia Cordata Extract,Sanguisorba Officinalis Root Extract, Sodium Carboxymethyl Beta-Glucan,Thymus Serpyllum Extract,Bht,Lactobacillus/Hibiscus Sabdariffa Flower Ferment Filtrate,Perilla Ocymoides Leaf Extract,Sodium Bicarbonate,Iris Florentina Root Extract,Sodium Benzoate,Ganoderma Lucidum (Mushroom) Stem Extract"))
    db.session.add(SkinProds(name="Acne+ 2% BHA and Azelaic Acid Acne Spot Treatment", brand_name="Skinfix", product_type="Acne Spot Treatment", ingredients="Water, Azelaic Acid, Caprylic/Capric Triglyceride, Kaolin, Propanediol, Stearyl Alcohol, C14-22 Alcohols, Niacinamide, Bentonite, Camellia Sinensis (Green Tea) Leaf Extract Glycyrrhiza Glabra (Licorice) Root Extract, Zinc PCA, Coco-Glucoside, Coconut Alcohol, Potassium Cetyl Phosphate, Phenoxyethanol, C12-20 Alkyl Glucoside, Citric Acid, Sodium Hydroxide, Potassium Sorbate, Ethylhexylglycerin, Stearyl Glycyrrhetinate, Amylopectin, Dextrin, Polydextrose, Glucose, Sodium Benzoate, Xanthan Gum, Glycerin"))
    db.session.add(SkinProds(name="FAB Pharma White Clay Acne Treatment Pads 2% Salicylic Acid", brand_name="First Aid Beauty", product_type="Acne Spot Treatment", ingredients="Water, Polysorbate 80, Phenoxyethanol, Sodium Hydroxide, Glycerin, Sodium Citrate, Kaolin, Salix Nigra (Willow) Bark Extract, Butylene Glycol, Rosmarinus Officinalis (Rosemary) Leaf Essential Oil, Potassium Sorbate, Sodium Benzoate, Camellia Sinensis Leaf Extract, Chrysanthemum Parthenium (Feverfew) Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Capryloyl Glycine, Hexylene Glycol, Symphytum Officinale Leaf Extract, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Sarcosine, Leuconostoc/Radish Root Ferment Filtrate, Enantia Chlorantha Bark Extract, Epilobium Angustifolium Flower/Leaf/Stem Extract, Cinnamomum Zeylanicum Bark Extract, Xanthan Gum, D-Limonene, Oleanolic Acid"))
    db.session.add(SkinProds(name="Barrier+ Foaming Oil Hydrating Cleanser", brand_name="Skinfix", product_type="Cleanser", skin_type="Normal, Dry, Combo", ingredients="Water, Sodium Methyl Cocoyl Taurate, Cocamidopropyl Hydroxysultaine, Glycerin, Caprylyl/Capryl Glucoside, Sodium Cocoyl Isethionate, Glycol Distearate, Betaine, Hydroxypropyl Guar Hydroxypropyltrimonium Chloride, Xanthan Gum, Propanediol, Citric Acid, Phenoxyethanol, Panthenol, Ethylhexylglycerin, Pentylene Glycol, Benzoic Acid, Chondrus Crispus (Carrageenan) Extract, Aloe Barbadensis Leaf Extract, Trisodium Ethylenediamine Disuccinate, Phenethyl Alcohol, Gluconolactone, Sodium Benzoate, Sodium Hyaluronate, Jojoba Seed Oil/Macadamia Seed Oil Esters, Squalane, Phytosteryl Macadamiate, Phytosterols, Tocopherol"))
    db.session.add(SkinProds(name="Lip Butter Balm", brand_name="Summer Fridays", product_type="Lip Treatment", skin_type="Normal, Oily, Combo", ingredients="Phytosteryl/Isostearyl/Cetyl/Stearyl Behenyl Dimer Dilinoleate, Diisostearyl Malate, Hydrogenated Polyisobutene, Polybutene, Hydrogenated Poly (C6-14 Olefin), Butyrospermum Parkii (Shea) Butter, Microcrystalline Wax/Cera Microcristallina/Cire Microcrystalline, Octyldodecanol, Synthetic Wax, Disteardimonium Hectorite, Polyglyceryl-2 Diisostearate, Mica, Vanillin, Astrocaryum Murumuru Seed Butter, Propylene Carbonate, Tocopherol, Sodium Hyaluronate"))
    db.session.add(SkinProds(name="Lip Sleeping Mask Intense Hydration with Vitamin C", brand_name="Laneige", product_type="Lip Treatment", ingredients="Diisostearyl Malate, Hydrogenated Polyisobutene, Phyto-Steryl/Isostearyl/Cetyl/Stearyl/Behenyl Dimer Dilinoleate, Hydrogenated Poly(C6-14 Olefin), Polybutene, Microcrystalline Wax/Cera Microcristallina/Cire Microcri Stalline, Butyrospermum Parkii (Shea) Butter, Synthetic Wax, Ethylene/Propylene/Styrene Copolymer, Sucrose Tetrastearate Triacetate, Mica, Euphorbia Cerifera (Candelilla) Wax/Candelilla Cera Hydrocarbons/Cire De Candelilla, Candelilla Wax Esters, Astrocaryum Murumuru Seed Butter, Titanium Dioxide, Fragrance/Parfum, Glyceryl Caprylate, Polyglyceryl-2 Diisostearate, Butylene/Ethylene/Styrene Copolymer, Copernicia Cerifera (Carnauba) Wax/Copernicia Cerifera Cera/Cire De Carnauba, Methicone, Polyglyceryl-2 Triisostearate, Cocos Nucifera (Coconut) Oil, Yellow 6 Lake, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Red 6, Ascorbic Acid, Water, Glycerin, Propanediol, BHT, Punica Granatum Fruit Juice, Rubus Idaeus (Raspberry) Juice, Vitis Vinifera (Grape) Juice"))
    db.session.add(SkinProds(name="Sugar Lip Balm Hydrating Treatment", brand_name="fresh", product_type="Lip Treatment", ingredients="Ricinus Communis (Castor) Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Cera Alba (Beeswax), Vitis Vinifera (Grape) Seed Oil, Helianthus Annuus (Sunflower) Seed Wax, Hydroxystearic Acid, Parfum (Fragrance), Oryza Sativa (Rice) Bran Wax, Persea Gratissima (Avocado) Oil, Limnanthes Alba (Meadowfoam) Seed Oil, Sucrose Tetrastearate Triacetate, Vaccinium Macrocarpon (Cranberry) Seed Oil, Citrus Limon (Lemon) Peel Oil, Helianthus Annuus (Sunflower) Seed Oil, Ribes Nigrum (Black Currant) Seed Oil, Rosmarinus Officinalis (Rosemary) Leaf Extract, Tocopherol, Ascorbyl Palmitate, Ascorbyl Tetraisopalmitate , Synthetic Fluorphlogopite, Ammonium Glycyrrhizate, Ethyl Vanillin, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Limonene, Citral, Linalool, Benzyl Alcohol, Geraniol"))
    db.session.add(SkinProds(name="Gentle Retinol Cream", brand_name="Good Molecules", product_type="Retinol", ingredients="Water, C13-16 Isoparaffin, Glycerin, Diheptyl Succinate, Heptyl Undecylenate, 1,2-hexanediol, Ammonium Acryloyldimethyltaurate/vp Copolymer, Polyglyceryl-10 Oleate, Propanediol, Vitis Vinifera, (Grape) Seed Oil, Caprylic/capric Triglyceride, Bakuchiol, Tocopherol, Acmella Oleracea Extract, Butylene Glycol, Retinol, Allantoin, Helianthus Annuus (Sunflower) Seed Oil, Capryloyl Glycerin/sebacic Acid Copolymer, Ethylhexylglycerin, Salix Alba (Willow) Bark Extract, Camellia Sinensis Leaf Extract, Lilium Candidum Bulb Extract"))
    db.session.add(SkinProds(name="Press Restart Gentle Retinol Serum", brand_name="Versed", product_type="Retinol", ingredients="Water, Helianthus Annuus (Sunflower) Seed Oil, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Retinol, Bakuchiol, Crithmum Maritimum Extract, Glycerin, Paeonia Suffruticosa Extract, Butyrospermum Parkii (Shea) Butter, Hydroxypropyl Cyclodextrin, Sodium Hyaluronate, Carica Papaya Extract, Xylitylglucoside, Anhydroxylitol, Xylitol, Hippophae Rhamnoides Oil, Tocopheryl Acetate, Opuntia Conccinellifera Fruit Extract, Rosa Canina Seed Oil, Chamomilla Recutita (Matricaria) Extract, Aloe Barbadensis Leaf Juice, Chlorophyll, Caprylic/Capric Triglyceride, Hydrogenated Vegetable Oil, Nylon-12, Isohexadecane, Polysorbate 80, Trehalose, Leuconostoc/Radish Root Ferment Filtrate, Phenoxyethanol, Ethylhexylglycerin"))
    db.session.add(SkinProds(name="1% Retinol Treatment", brand_name="Paula's Choice", product_type="Retinol", ingredients="Salix Alba Extract, Dipotassium Glycyrrhizate, Arctium Lappa, Cetyl Esters, Tetrahexyldecyl Ascorbate, Retinol, Glycine Soja Sterols, Glycerin, Sodium Hyaluronate, Allantoin, Avena Sativa Kernel Extract, Palmitoyl Tetrapeptide-7, Lecithin, Dimethicone, Palmitoyl Tripeptide-1, Laurdimonium Hydroxypropyl Hydrolyzed Soy Protein, Glycyrrhiza Glabra, Ceramide NS, Palmitoyl Hexapeptide-12, Tocopheryl Acetate"))
    db.session.add(SkinProds(name="Micro-Dose Anti-Aging Retinol Serum with Ceramides and Peptide", brand_name="Kiehl's", product_type="Retinol", ingredients="Water, Glycerin, Butylene Glycol, Pentylene Glycol, Niacinamide, Cetyl Alcohol, Isohexadecane, Isononyl Isononanoate, Diisopropyl Sebacate, 2-Oleamido-1,3-Octadecanediol, 4-T-Butylcyclohexanol, Acetyl Dipeptide-1 Cetyl Ester, Adenosine, Ceramide Np, Hydroxypalmitoyl Sphinganine, Lauroyl Lysine, Octyldodecanol, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Sodium Chloride, Sodium Hyaluronate, Sodium Hydroxide, Trisodium Ethylenediamine Disuccinate, Retinol, Tocopherol, Dicaprylyl Ether, Ammonium Polyacryloyldimethyl Taurate, Behenyl Alcohol, Caprylyl Glycol, Carbomer, Cetearyl Alcohol, Cetearyl Glucoside, Glycine Soja Oil/Soybean Oil, Helianthus Annuus Seed Oil/Sunflower Seed Oil, Hydroxyethylcellulose, Lecithin, Phenethyl Alcohol, Poloxamer 188, Polycaprolactone, Sorbitan Laurate, Steareth-100, CI 40800/Beta-Carotene, Chlorphenesin, Phenoxyethanol"))
    db.session.add(SkinProds(name="Creamy Eye Treatment with Avocado", brand_name="Kiehl's", product_type="Eye Cream", ingredients="Water, Butyrospermum Parkii Butter/Shea Butter, Butylene Glycol, Tridecyl Stearate, Isodecyl Salicylate, Peg-30,Dipolyhydroxystearate, Tridecyl Trimellitate, Persea Gratissima Oil/Avocado Oil, Isocetyl Stearoyl Stearate, Propylene Glycol, Dipentaerythrityl Hexacaprylate/Hexacaprate, Sorbitan Sesquioleate, Magnesium Sulfate, Phenoxyethanol, Hydrogenated Castor Oil, Sodium Pca, Ozokerite, Methylparaben, Tocopheryl Acetate, Isopropyl Palmitate, Disodium Edta, Copper Pca, Butylparaben, Ethylparaben, Propylparaben, Helianthus Annuus Seed Oil/Sunflower Seed Oil, Ci 75130/Beta-Carotene, Tocopherol, Citric Acid"))
    db.session.add(SkinProds(name="Bright Start Retinol Alternative Brightening Eye Cream", brand_name="ILIA", product_type="Eye Cream", ingredients="Water, Caprylic/Capric Triglyceride, Persea Gratissima (Avocado) Oil, Propanediol, Glycerin, Pentylene Glycol, Cetearyl Alcohol, Candelilla/Jojoba/Rice Bran Polyglyceryl-3 Esters, Jojoba Oil/Macadamia Seed Oil Esters, Brassica Campestris/Aleurites Fordi Oil Copolymer, Silica, Glyceryl Stearate, Sodium Polyacryloyldimethyl Taurate, Behenyl Alcohol, Caffeine, Moringa Oil/Hydrogenated Moringa Oil Esters, Sodium Stearoyl Lactylate, Mica, Hydroxyacetophenone, Caprylyl Glycol, 1,2-Hexanediol, Squalene, Caprylic/Capric/Succinic Triglyceride, Xanthan Gum, Citric Acid, Sodium Phytate, Phytosteryl Macadamiate, Persea Gratissima (Avocado) Fruit Extract, Crithmum Maritimum Extract, Phytosterols, Tocopherol, Acetyl Hexapeptide-8, Sodium Citrate, Titanium Dioxide, Iron Oxide"))
    db.session.add(SkinProds(name="Lip Wrap Overnight Treatment", brand_name="ILIA", product_type="Lip Treatment", ingredients="Caprylic/Capric Triglyceride, Mango Butter Dimer Dilinoleyl Esters/Dimer Dilinoleate Copolymer, Capryloyl Glycerin/Sebacic Acid Copolymer, Bis-Diglyceryl Polyacyladipate-2, Polyglyceryl-10 Decaoleate, Polyglyceryl-10 Pentaoleate, Polyglyceryl-10 Pentaisostearate, C10-18 Triglycerides, Butyrospermum Parkii (Shea) Butter, Cera Alba/Beeswax/Cire d'abeille, Glyceryl Stearate SE, Hydroxystearic Acid, Aroma, Cocos Nucifera (Coconut) Oil, Lactobacillus/Papaya Fruit Ferment Extract, Silica, Polyhydroxystearic Acid, Ricinus Communis (Castor) Seed Oil, Carica Papaya (Papaya) Seed Oil, Sodium Hyaluronate, Tocopherol, Hydrogenated Castor Oil, Stevia Rebaudiana Leaf/Stem Extract, Gardenia Taitensis Flower Extract, Salicornia Herbacea Extract, Undaria Pinnatifida Extract, Geraniol, Limonene, Linalool, Titanium Dioxide"))
    db.session.add(SkinProds(name="Daily Glycolic Cleanser", brand_name="Dermalogica", product_type="Cleanser", skin_type="Normal, Combo, Oily", ingredients="Water, Cocamidopropyl Hydroxysultaine, Glycolic Acid, Glycerin, Peg-6"))
    db.session.add(SkinProds(name="Volcanic AHA Pore Clearing Clay Mask", brand_name="innisfree", product_type="Face Mask", skin_type="Normal, Combo, Oily", ingredients="Water, Titanium Dioxide, Butylene Glycol, Silica, Glycerin, Trehalose, Volcanic Ash, Polyvinyl Alcohol, Bentonite, Kaolin, Caprylic/Caprictriglyceride, Glyceryl Stearate, Stearic Acid, Cetearylalcohol, Pvp, 1,2-Hexanediol, Peg-100 Stearate, Polysorbate-60, Hydrogenated Vegetableoil, Xanthan Gum, Juglans Regia (Walnut) Shell Powder,Sorbitan Stearate, Zea Mays (Corn) Starch, Polyacrylate-13, Polysorbate 20, Mannitol, Microcrystalline Cellulose, Lactic Acid/Glycolic Acidcopolymer, Lactic Acid, Polyisobutene, Iron Oxides, Menthoxypropanediol, Tetrasodium Pyrophosphate, Disodium Edta, Ethylhexylglycerin, Sorbitan Isostearate, Aluminum Hydroxide, Triethoxycaprylylsilane, Tocopherol"))
    db.session.add(SkinProds(name="Watermelon Glow Hyaluronic Clay Pore-Tight Facial Mask", brand_name="Glow Recipe", product_type="Face Mask", ingredients="Water, Glycerin, Kaolin, Stearyl Alcohol, Hydroxypropyl Starch Phosphate, Bentonite, Caprylic/Capric Triglyceride, Glyceryl Stearate SE, Citrullus Lanatus (Watermelon) Fruit Extract, Gluconolactone, Hydrated Silica, Sea Water/Maris Aqua/Eau De Mer, Salix Alba (Willow) Bark Extract, Sodium Stearoyl Lactylate, Xanthan Gum, Lactobacillus/Watermelon Fruit Ferment Extract, Sodium Hyaluronate, Hydrolyzed Sodium Hyaluronate, Bambusa Arundinacea (Bamboo) Stem Extract, Lycium Barbarum (Goji Berry) Fruit Extract, Leuconostoc/Radish Root Ferment Filtrate, Caprylyl Glycol, 1,2-Hexanediol, Citric Acid, Maltodextrin, Eclipta Prostrata Extract, Glucose, Sodium Phytate, Silica, Melia Azadirachta Leaf Extract, Potassium Sorbate, Hexylene Glycol, Moringa Oleifera Seed Oil, Vaccinium Corymbosum (Blueberry) Seed, Hydroxyacetophenone, Carrageenan, Titanium Dioxide, Phenoxyethanol, Fragrance/Parfum"))
    db.session.add(SkinProds(name="Superberry Hydrate + Glow Dream Night Mask with Vitamin C", brand_name="Youth To The People", product_type="Face Mask", ingredients="Water, Glycerin, Helianthus Annuus (Sunflower) Seed Oil, Isopropyl Myristate, Glyceryl Stearate, Betaine, Cetyl Alcohol, Stearic Acid, Tetrahexyldecyl Ascorbate (Vitamin C), Opuntia Tuna (Prickly Pear) Flower/Stem Extract, Euterpe Oleracea (Açaí) Fruit Extract, Lycium Barbarum (Goji) Fruit Extract, Aristotelia Chilensis (Maqui) Fruit Extract, Moringa Oleifera Leaf Extract, Glyceryl Stearate Citrate, Tocopheryl Acetate (Vitamin E), Glyceryl Laurate, Squalane, Carbomer, Hyaluronic Acid, Allantoin, Panthenol (Vitamin B5), Ethylhexylglycerin, Xanthan Gum, Phenoxyethanol, Riboflavin (Vitamin B2), Triethyl Citrate, Citrus Aurantium Dulcis Peel Oil, Gamma-Undecalactone, Gamma-Decalactone, Tocopherol, Limonene"))
    db.session.add(SkinProds(name="Superberry Hydrate + Glow Dream Oil", brand_name="Youth To The People", product_type="Face Oil", ingredients="Helianthus Annuus (Sunflower) Seed Oil, Dicaprylyl Carbonate, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane Olive, Tocopherol (Vitamin E), Natural Fragrance, Aristotelia Chilensis (Maqui) Fruit Extract, Euterpe Oleracea Fruit (Acai) Extract, Lycium Barbarum (Goji) Fruit Extract, Moringa Oleifera Leaf Extract, Opuntia Tuna (Prickly Pear) Flower/Stem Extract, Borago Officinalis (Borage) Seed Oil, Linum Usitatissimum (Flaxseed) Seed Oil, Oenothera Biennis (Evening Primrose) Oil, Olea Europaea (Olive) Fruit Oil, Rosa Canina (Rosehip) Fruit Oil, Punica Granatum (Pomegranate) Seed Oil, Vaccinium Macrocarpon (Cranberry) Seed Oil, Amylcinnamyl Alcohol, Citral, Citronellol, Hexyl Cinnamal, Hydroxycitronellal, Limonene, Linalool"))
    db.session.add(SkinProds(name="Mandelic Acid + Superfood Unity Exfoliant", brand_name="Youth To The People", product_type="Exfoliant", ingredients="Water, Helianthus Annuus (Sunflower) Seed Oil, Stearic Acid, Glycerin, Glyceryl Stearate, Cetyl Alcohol, Ascorbic Acid (Vitamin C), Lecithin, Panthenol (Vitamin B5), Sodium Hyaluronate Crosspolymer, Tocopheryl Acetate (Vitamin E), Phenoxyethanol, Hydroxyethylcellulose, Potassium Sorbate, Aloe Barbadensis (Aloe) Leaf Extract, Brassica Oleracea Capitata (Kale) Leaf Extract, Camellia Sinensis (Green Tea) Leaf Extract, Chamomilla Recutita (Matricaria) Flower Extract*, Medicago Sativa (Alfalfa) Leaf Extract, Spinacia Oleracea (Spinach) Leaf Extract, Natural Fragrance, Pentylene Glycol, Ethylhexylglycerin, Magnesium Chloride, Palmitoyl Dipeptide-5 Diaminobutyroyl Hydroxythreonine, Palmitoyl Tripeptide-5, Tetradecyl Aminobutyroylvalylaminobutyric Urea Trifluoroacetate, Benzyl Benzoate, Citronellol, Hexyl Cinnamal, Limonene, Linalool"))
    db.session.add(SkinProds(name="Ultralight Moisture-Boosting Botanical Oil", brand_name="The Outset", product_type="Face Oil", ingredients="Caprylic/Capric Triglyceride, Squalane, Hydrogenated Ethylhexyl Olivate, Diheptyl Succinate, Simmondsia Chinensis (Jojoba) Seed Oil, Crambe Abyssinica Seed Oil, Euterpe Oleracea Fruit Oil, Helianthus Annuus (Sunflower) Seed Oil, Vitis Vinifera (Grape) Seed Oil, Sclerocarya Birrea Seed Oil, Persea Gratissima (Avocado) Oil, Cassia Angustifolia Seed Polysaccharide, Argania Spinosa Kernel Oil, Brassica Campestris (Rapeseed) Seed Oil, Moringa Oleifera Seed Oil, Hippophae Rhamnoides Oil, Linum Usitatissimum (Linseed) Seed Oil, Opuntia Ficus-Indica Seed Oil, Sesamum Indicum (Sesame) Seed Oil, Emblica Officinalis Fruit Extract, Capryloyl Glycerin/Sebacic Acid Copolymer, Hydrogenated Olive Oil Unsaponifiables, Water"))
    db.session.add(SkinProds(name="Nourishing Squalane Daily Moisturizer", brand_name="The Outset", product_type="Moisturizer", ingredients="Water, Caprylic/Capric Triglyceride, Pentylene Glycol, Glycerin, Ethylhexyl Palmitate, Cetearyl Alcohol, Squalane, Cassia Angustifolia Seed Polysaccharide, Helianthus Annuus (Sunflower) Seed Oil, Cocos Nucifera (Coconut) Oil, Carthamus Tinctorius (Safflower) Seed Oil, Persea Gratissima (Avocado) Oil, Humulus Lupulus (Hops) Extract, Helianthus Annuus (Sunflower) Extract, Helianthus Annuus (Sunflower) Seed Wax, Rosmarinus Officinalis (Rosemary) Leaf Extract, Aloe Barbadensis Leaf Juice, Prunus Insititia Seed Oil, Oryza Sativa (Rice) Bran Extract, Fucus Vesiculosus Extract, Leuconostoc/Radish Root Ferment Filtrate, Leontopodium Alpinum Extract, Glycine Soja (Soybean) Oil, Jojoba Esters, Dicaprylyl Ether, Diheptyl Succinate, Glyceryl Stearate, Carbomer, Phenoxyethanol, Citric Acid, Hydrogenated Vegetable Oil, Xanthan Gum, Polyglycerin-3, Caprylyl Glycol, Capryloyl Glycerin/Sebacic Acid Copolymer, Tocopheryl Acetate, Tocopherol, Tetrasodium Glutamate Diacetate, Potassium Hydroxide, Potassium Sorbate, Sodium Benzoate, Sodium Formate, Sodium Glycolate, Sodium Hydroxide, Sodium Stearoyl Glutamate"))
    db.session.add(SkinProds(name="Firming Vegan Collagen Prep Serum", brand_name="The Outset", product_type="Serum", ingredients="Water, Propanediol, Glycerin, Triheptanoin, Coco-Caprylate/Caprate, Sodium Polyacryloyldimethyl Taurate, Capryloyl Glycerin/Sebacic Acid Copolymer, Cassia Angustifolia Seed Polysaccharide, Helianthus Annuus (Sunflower) Seed Oil, Heterotheca Inuloides Flower Extract, Chenopodium Quinoa Seed Extract, Poncirus Trifoliata Fruit Extract, Hydrolyzed Brassica Napus Seedcake Extract, SR-Hydrozoan Polypeptide-1, Castor Oil/IPDI Copolymer, Diheptyl Succinate, Phenoxyethanol, Dilinoleic Acid/Butanediol Copolymer, Caprylyl Glycol, Hydrolyzed Jojoba Esters, Lysolecithin, Sclerotium Gum, Tetrahexyldecyl Ascorbate, Tocopheryl Acetate, Tetrasodium Glutamate Diacetate, Pullulan, Xanthan Gum, Jojoba Esters, Silica, Citric Acid, Sodium Benzoate, Sodium Formate, Sodium Glycolate, Sodium Hydroxide, Sodium PCA, Potassium Hydroxide, Potassium Sorbate"))
    db.session.add(SkinProds(name="Gentle Micellar Antioxidant Cleanser", brand_name="The Outset", product_type="Cleanser", ingredients="Water, Propanediol, Glycerin, Triheptanoin, Coco-Caprylate/Caprate, Sodium Polyacryloyldimethyl Taurate, Capryloyl Glycerin/Sebacic Acid Copolymer, Cassia Angustifolia Seed Polysaccharide, Helianthus Annuus (Sunflower) Seed Oil, Heterotheca Inuloides Flower Extract, Chenopodium Quinoa Seed Extract, Poncirus Trifoliata Fruit Extract, Hydrolyzed Brassica Napus Seedcake Extract, SR-Hydrozoan Polypeptide-1, Castor Oil/IPDI Copolymer, Diheptyl Succinate, Phenoxyethanol, Dilinoleic Acid/Butanediol Copolymer, Caprylyl Glycol, Hydrolyzed Jojoba Esters, Lysolecithin, Sclerotium Gum, Tetrahexyldecyl Ascorbate, Tocopheryl Acetate, Tetrasodium Glutamate Diacetate, Pullulan, Xanthan Gum, Jojoba Esters, Silica, Citric Acid, Sodium Benzoate, Sodium Formate, Sodium Glycolate, Sodium Hydroxide, Sodium PCA, Potassium Hydroxide, Potassium Sorbate"))
    db.session.add(SkinProds(name="Exfoliating Revitalizing & Energizing Caffeine Micro Polish", brand_name="The Outset", product_type="Exfoliant", ingredients="Glycerin, Caprylic/Capric Triglyceride, Water, Sucrose Stearate, Perlite, Helianthus Annuus (Sunflower) Seed Oil, Cassia Angustifolia Seed Polysaccharide, Caffeine, Chamomilla Recutita (Matricaria) Flower Extract, Camellia Sinensis Leaf Extract, Microcrystalline Cellulose, Allantoin, Ethylhexylglycerin, Chlorphenesin, Xanthan Gum, Cellulose Gum, Tocopherol"))
    db.session.add(SkinProds(name="Lemonade Smoothing Scrub", brand_name="OLEHENRIKSEN", product_type="Exfoliant", ingredients="Water, Glycerin, Glycolic Acid, Sucrose, Hydrated Silica, Polyglyceryl-10 Dipalmitate, Propanediol, Lactic Acid, Sodium Cocoyl Isethionate, Polyacrylate Crosspolymer-6, Sodium Hydroxide, Sodium Lactate, Acrylamide/Sodium Acryloyldimethyltaurate Copolymer, Citrus Limon (Lemon) Peel Powder, Citrus Limon (Lemon) Fruit Extract, Ocimum Sanctum Leaf Extract, Chamomilla Recutita (Matricaria) Flower Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Saccharum Officinarum (Sugarcane) Extract/Extrait De Canne À Sucre, Citrus Aurantifolia (Lime) Peel Extract, Santalum Album (Sandalwood) Extract, Citrus Limon (Lemon) Peel Oil, Citrus Aurantium Bergamia (Bergamot) Peel Oil, Leuconostoc/Radish Root Ferment Filtrate, Coconut Acid, Sodium Riboflavin Phosphate, Dimethylhydroxy Furanone, Isohexadecane, Polysorbate 80, Sodium Isethionate, Sorbitan Oleate, Triethyl Citrate, Vanillin, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Caprylyl Glycol, Phenoxyethanol, Limonene, Linalool, Citral"))
    db.session.add(SkinProds(name="Ceramidin Skin Barrier Moisturizing Cream", brand_name="Dr. Jart+", product_type="Moisturizer", ingredients="Water, Glycerin, Caprylic/Capric Triglyceride, Dipropylene Glycol, Cetearyl Alcohol, Hydrogenated Polydecene, Methyl Trimethicone, Hydrogenated Poly(C6-14 Olefin), Butyrospermum Parkii (Shea) Butter, 1,2-Hexanediol, Phenyl Trimethicone, Dicaprylyl Ether, Cetearyl Olivate, Panthenol, Glyceryl Stearate, Behenyl Alcohol, Sorbitan Olivate, Theobroma Cacao (Cocoa) Seed Extract, 2,3-Butanediol, Cetearyl Glucoside, Ceramide NP, Ceramide NG, Ceramide NS, Ceramide AS, Ceramide AP, Cholesterol, Pentaerythrityl Distearate, Hydrogenated Lecithin, Palmitic Acid, Stearic Acid, Microcrystalline Cellulose, Glyceryl Stearate Se, Ammonium Acryloyldimethyltaurate/VP Copolymer, Cellulose Gum, Dextrin, Glyceryl Polymethacrylate, Pelargonium Graveolens Flower Oil, Olea Europaea (Olive) Fruit Oil, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Salvia Officinalis (Sage) Oil, Citronellol, Tocopherol, Yellow 5"))
    db.session.add(SkinProds(name="Ceramidin Eye Cream with Niacinamide", brand_name="Dr. Jart+", product_type="Eye Cream", ingredients="Water, Glycerin, Betaine, Cyclohexasiloxane, Squalane, Pentaerythrityl Distearate, Methylpropanediol, Niacinamide, Dicaprylyl Ether, Ammonium Acryloyldimethyltaurate/VP Copolymer, Cetearyl Glucoside, Cetearyl Alcohol, Panthenol, 1,2-Hexanediol, Sodium Stearoyl Glutamate, Ceramide NP, Dipropylene Glycol, Hydroxyacetophenone, Mannitol, Zea Mays (Corn) Starch, Microcrystalline Cellulose, Ethylhexylglycerin, Pelargonium Graveolens Flower Oil, Hydrogenated Lecithin, Allantoin, Adenosine, Dextrin, Theobroma Cacao (Cocoa) Seed Extract, Disodium EDTA, Pyrus Malus (Apple) Fruit Extract, Salvia Officinalis (Sage) Oil, Gardenia Florida Fruit Extract, Pogostemon Cablin Oil, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Tocopherol, Glyceryl Stearate, Ceramide AP, Cholesterol, Ceramide AS, Ceramide NS, Ceramide EOP"))
    db.session.add(SkinProds(name="Dermask Water Jet Vital Hydra Solution", brand_name="Dr. Jart+", product_type="Face Mask", ingredients="Water, Glycerin, Butylene Glycol, Alcohol, Panthenol, Betaine, Xylitylglucoside, Anhydroxylitol, Xylitol, Hydrolyzed Hyaluronic Acid, Algae Extract, Laminaria Japonica Extract, Chlorphenesin, Hydroxyethylcellulose, Disodium EDTA, Xanthan Gum, PEG-60 Hydrogenated Castor Oil, Glycyrrhiza Glabra (Licorice) Root Extract, Zingiber Officinale (Ginger) Root Extract, Schizandra Chinensis Fruit Extract, Coptis Japonica Root Extract, Camellia Sinensis Leaf Extract, Caprylyl Glycol, 1,2-Hexanediol, Dipotassium Glycyrrhizate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Carbomer, Arginine, Citrus Grandis (Grapefruit) Seed Extract, Acorus Calamus Root Extract, Perilla Ocymoides Leaf Extract, Cyclopentasiloxane, Cyclohexasiloxane, PEG-10 Dimethicone/Vinyl Dimethicone Crosspolymer, Pelargonium Graveolens Flower Oil"))
    db.session.add(SkinProds(name="Cicapair Tiger Grass Serum", brand_name="Dr. Jart+", product_type="Serum", ingredients="Water, Dipropylene Glycol, Glycerin, Butylene Glycol, Propanediol, Eryngium Maritimum Callus Culture Filtrate, 1,2-Hexanediol, Niacinamide, Houttuynia Cordata Extract, Ilex Aquifolium (Holly) Leaf Extract, Achillea Millefolium Oil, Panthenol, Chondrus Crispus Extract, C12-14 Pareth-12, Saccharum Officinarum (Sugarcane) Extract/Extrait de canne à sucre, Streptococcus Thermophilus Ferment, Carbomer, Tromethamine, Madecassoside, Melia Azadirachta Leaf Extract, Xanthan Gum, Ethylhexylglycerin, Adenosine, Lavandula Angustifolia (Lavender) Oil, DNA, Disodium EDTA, Melia Azadirachta Flower Extract, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Asiaticoside, Dextrin, Theobroma Cacao (Cocoa) Extract, Centella Asiatica Leaf Extract, Hedera Helix (Ivy) Extract, Asiatic Acid, Madecassic Acid, Calcium Chloride, Centella Asiatica Extract, Magnesium Sulfate"))
    db.session.add(SkinProds(name="Glycolic Acid 7% Toning Solution", brand_name="The Ordinary", product_type="Exfoliant", ingredients="Water, Glycolic Acid, Rosa damascena flower water, Centaurea cyanus flower water, Aloe Barbadensis Leaf Water, Propanediol, Glycerin, Triethanolamine, Aminomethyl Propanol, Panax Ginseng Root Extract, Tasmannia Lanceolata Fruit/Leaf Extract, Aspartic Acid, Alanine, Glycine, Serine, Valine, Isoleucine, Proline, Threonine, Histidine, Phenylalanine, Glutamic Acid, Arginine, PCA, Sodium PCA, Sodium Lactate, Fructose, Glucose, Sucrose, Urea, Hexyl Nicotinate, Dextrin, Citric Acid, Polysorbate 20, Gellan Gum, Trisodium Ethylenediamine Disuccinate, Sodium Chloride, Hexylene Glycol, Potassium Sorbate, Sodium Benzoate, 1,2-Hexanediol, Caprylyl Glycol"))
    db.session.add(SkinProds(name="Multi-Peptide + HA Serum", brand_name="The Ordinary", product_type="Serum", ingredients="Water, Glycerin, Lactococcus Ferment Lysate, Acetyl Hexapeptide-8, Pentapeptide-18, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7, Palmitoyl Tripeptide-38, Dipeptide Diaminobutyroyl Benzylamide Diacetate, Acetylarginyltryptophyl Diphenylglycine, Sodium Hyaluronate Crosspolymer, Sodium Hyaluronate, Allantoin, Glycine, Alanine, Serine, Valine, Isoleucine, Proline, Threonine, Histidine, Phenylalanine, Arginine, Aspartic Acid, Trehalose, Fructose, Glucose, Maltose, Urea, Sodium PCA, PCA, Sodium Lactate, Citric Acid, Hydroxypropyl Cyclodextrin, Sodium Chloride, Sodium Hydroxide, Butylene Glycol, Pentylene Glycol, Acacia Senegal Gum, Xanthan Gum, Carbomer, Polysorbate 20, PPG-26-Buteth-26, PEG-40 Hydrogenated Castor Oil, Trisodium Ethylenediamine Disuccinate, Ethoxydiglycol, Sodium Benzoate, Caprylyl Glycol, Ethylhexylglycerin, Phenoxyethanol, Chlorphenesin"))
    db.session.commit()
    return {"message": "Initialized skincare products data in table successfully!"}

with app.app_context():
    # drops schema if exists and recreates database
    # db.drop_all()
    db.create_all()
    dbinit()

# A route to return all of available entries in our catalog.
@app.route('/api/v2/resources/skincareproducts/all', methods=['GET'])
def api_all():
    all_skinprods = []
    for skinprod in db.session.query(SkinProds).all():
        del skinprod.__dict__['_sa_instance_state']
        all_skinprods.append(skinprod.__dict__)
    return jsonify(all_skinprods)

#error handler for any exception
@app.errorhandler(404)
def page_not_found(e):
    return "<h1>404</h1><p>The resource could not be found</p>", 404

# queries SkinProds database after building query filter using params passed if HTTP "GET" request 
@app.route('/api/v2/resources/skincareproducts', methods=['GET'])
def api_filter():
    query_parameters = request.args
    for key in query_parameters:
        print (f'argument {key} and value {query_parameters.get(key)}', flush=True)

    # handle filter of ingredient(s) specified here-- gets parameters values from url
    id = query_parameters.get('id')
    name = query_parameters.get('name')
    #specify >1 brand name
    brand_name_list = query_parameters.get('brand')
    product_type = query_parameters.get('productType')
    # specify >1 skin type (ex. "Dry" & "Sensitive")--> check if "getlist" works
    skin_types_list = query_parameters.get('skinTypes')
    # how to handle ingredients(be able to have user specify >1 ingredient at a time)
    ingredients_list = query_parameters.get('ingredients')

    query = db.session.query(SkinProds)
    if id:
        query = query.filter(SkinProds.id==id) #search for product by id

    if name:
        query = query.filter(SkinProds.name==name) #search for exact product name
        #query = query.filter(SkinProds.name.ilike(f'%{str(name)}%'))

    if brand_name_list:
        #if multiple brand specified:
        try:
            search_brands = brand_name_list.split(",")
            brand_list = [br.strip() for br in search_brands]
            print (f'brand list{brand_list}', flush=True)
            filter_list = [SkinProds.brand_name.ilike(f'%{str(brand)}%') for brand in brand_list] #ilike allows user to enter brand name without exact capitalization
            print (f'filter list{filter_list}', flush=True)
            query = query.filter(or_(*filter_list)) #gets results when any brand name specified is recognized in database
        except:
            #if only one brand specified:
            brand = brand_name_list
            query = query.filter(SkinProds.brand_name.ilike("%"+str(brand)+"%")) 
   
    if product_type:
        query = query.filter(SkinProds.product_type.ilike("%"+str(product_type)+"%")) #ilike for nonspecific capitalization

    if skin_types_list:
        #if multiple skin types specified:
        try:
            search_skin_types = skin_types_list.split(",")
            for type in search_skin_types:
                query = query.filter(SkinProds.skin_type.ilike("%"+str(type)+"%")) #gets results when all skin types specified are matched
        except:
            #if only one skin type specified:
            type = skin_types_list
            query = query.filter(SkinProds.skin_type.ilike("%"+str(type)+"%"))

    if ingredients_list:
        #handles entry of multiple ingredients that are unwanted
        try:
            search_ingredients = ingredients_list.split(",")
            refined_search_ingredients = [ing.strip() for ing in search_ingredients]
            filter_list = [~SkinProds.ingredients.ilike(f'%{str(ingredient)}%') for ingredient in refined_search_ingredients]
            query = query.filter(and_(*filter_list))
        except:
            #if only one unwanted ingredient specified
            ingredient = ingredients_list
            query = query.filter(~SkinProds.ingredients.ilike("%"+str(ingredient)+"%"))

    # now the built query is run
    results = query.all()
    response_skinprods = []
    for skinprod in results:
        del skinprod.__dict__['_sa_instance_state']
        response_skinprods.append(skinprod.__dict__)
   
    return jsonify(response_skinprods) #returns jsonified API response


@app.route('/api/v2/resources/skincareproducts', methods=['POST'])
def add_skinprod():
    # Receives data in JSON format for a HTTP "POST" request
    if not request.is_json: #error message if data not passed in JSON format
        return "<p>The data you wish to add is not of type JSON<\p>"
    
    new_sp = request.get_json()
    db.session.add(SkinProds(new_sp['name'], new_sp['brand_name'], new_sp['product_type'], new_sp['ingredients'], new_sp['skin_type']))
    db.session.commit()
    
    return {"message": f"Skincare product {new_sp['name']} successfully added to SkinProds database"}

@app.route('/api/v2/resources/skincareproducts/<sp_id>', methods=['GET', 'PUT', 'DELETE'])
def handle_skinprod(sp_id):
    skinprod = SkinProds.query.get_or_404(sp_id)

    if request.method == 'GET': #gets product details by id without specifying query param "id"
       
        return jsonify(skinprod.serialize)

    elif request.method == 'PUT':
        updated_sp_data = request.get_json() #gets new information for existing product (in JSON type)
        # uses information to update each attribute of skin product
        skinprod.name = updated_sp_data['name']
        skinprod.brand_name = updated_sp_data['brand_name']
        skinprod.product_type = updated_sp_data['product_type']
        skinprod.skin_type = updated_sp_data['skin_type']
        skinprod.ingredients = updated_sp_data['ingredients']
        db.session.add(skinprod) #replaces old product with new, updated product
        db.session.commit() #commits changes
        return {"message": f"Skincare product {skinprod.name} successfully updated"}

    elif request.method == 'DELETE': # deletes specified product using product id info
        db.session.delete(skinprod)
        db.session.commit()
        return {"message": f"Skincare product {skinprod.name} successfully deleted."}

if __name__ == "__main__":
    app.run(debug=True, threaded=True, port=5000)